version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "1234:1234"
  
  backend:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - FLASK_HOST=backend


  mongo:
    image: mongo:6.0.13
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: